### ISSUE TITLE
Confused with REST API

### ISSUE THREAD

**Issue by gigilsu** [CallFire/CallFire-PHP-SDK#24]
I am trying to send a broadcast text but I find the documentation confusing. When I try to send a text I get an object with protected values which I cannot do anything with. If there is any documentation on how to send a broadcast text, please point me to it. The response that I got from the SendText request was an object full of protected properties, which I cannot do anything with. The only thing I have managed to accomplish is to set a campaign. I sent a request to add contacts to that campaign, but I do not see where that happened. I also did not manage to actually start the campaign and send the text message to the contact list. I am in search of examples on how to set up a campaign, add contacts, and send messages via shortcode to the contacts in that campaign.

**Comment by TheFrozenFire** [comment]
Answered in HipChat. Please feel free to reach out again if you have any issues. :)
